export const BROWSE_TRADE_ADS_ACTIONS = {
  SWITCH_TRADE_TYPE: 'SWITCH_TRADE_TYPE',
  CHANGE_AMOUNT: 'CHANGE_AMOUNT',
  CHANGE_CURRENCY: 'CHANGE_CURRENCY',
  SELECT_PAY_METHODS: 'SELECT_PAY_METHODS'
};

export const APP_ACTIONS = {
  LOAD_USER: 'LOAD_USER'
};
