import React, { ReactElement } from 'react';
import AccountActivity from './account-activity';
import { Button, TextField } from '@mui/material';
import Image from 'next/image';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import { SecurityWrapper } from '../account-settings.styles';
import { Wrapper } from '../../styles/layout.styles';
import { CustomizableText } from '../../styles/text.styles';

const SecurityComponent = (): ReactElement => {
  return (
    <SecurityWrapper>
      <CustomizableText
        $margin="0px"
        $size="20px"
        $fontWeight="700"
        $lineHeight="32px"
        $color="#000759">
        Two-factor authentication (2FA) settings
      </CustomizableText>
      <Wrapper $mobileMarginB="20px" $marginB="70px" $marginT="10px">
        <CustomizableText
          $margin="0px"
          $size="14px"
          $fontWeight="400"
          $lineHeight="20px"
          $color="#444">
          Set up your 2FA and make your account more secure.
        </CustomizableText>
      </Wrapper>
      <Wrapper
        $display="flex"
        $align="center"
        $gap="20px"
        $border="1px solid #D0D5DD"
        $paddingB="17px"
        $paddingL="25px"
        $paddingR="25px"
        $paddingT="17px"
        $borderRadius="8px">
        <Wrapper
          $bg="#000759"
          $borderRadius="8px"
          $paddingB="12px"
          $paddingL="12px"
          $paddingR="12px"
          $paddingT="12px"
          $display="flex"
          $align="center"
          $justify="center">
          <Image src={'/key.svg'} alt="key" width={24} height={24} />
        </Wrapper>
        <Wrapper $mobileWidth="100%" $width="80%">
          <CustomizableText $size="16px" $lineHeight="24px" $fontWeight="600" $margin="0px">
            Authentication App
          </CustomizableText>
          <Wrapper $marginT="5px">
            <CustomizableText
              $margin="0px"
              $size="14px"
              $fontWeight="400"
              $lineHeight="20px"
              $color="#444">
              Time-bound code generated by your authentication app.
            </CustomizableText>
          </Wrapper>
        </Wrapper>
        <ArrowForwardIcon sx={{ color: '#98A2B3' }} />
      </Wrapper>
      <Wrapper
        $marginB="50px"
        $mobileMarginB="20px"
        $marginT="30px"
        $display="flex"
        $align="center"
        $gap="20px"
        $border="1px solid #D0D5DD"
        $paddingB="17px"
        $paddingL="25px"
        $paddingR="25px"
        $paddingT="17px"
        $borderRadius="8px">
        <Wrapper
          $display="flex"
          $align="center"
          $justify="center"
          $bg="#000759"
          $borderRadius="8px"
          $paddingB="12px"
          $paddingL="12px"
          $paddingR="12px"
          $paddingT="12px">
          <Image src={'/email.svg'} alt="key" width={24} height={24} />
        </Wrapper>
        <Wrapper $mobileWidth="100%" $width="80%">
          <CustomizableText $size="16px" $lineHeight="24px" $fontWeight="600" $margin="0px">
            Email
          </CustomizableText>
          <Wrapper $marginT="5px">
            <CustomizableText
              $margin="0px"
              $size="14px"
              $fontWeight="400"
              $lineHeight="20px"
              $color="#444">
              A unique time-bound code sent via Email.
            </CustomizableText>
          </Wrapper>
        </Wrapper>
        <ArrowForwardIcon sx={{ color: '#98A2B3' }} />
      </Wrapper>
      <CustomizableText
        $margin="0px"
        $size="20px"
        $fontWeight="700"
        $lineHeight="32px"
        $color="#000759">
        Change Password
      </CustomizableText>
      <Wrapper $mobileMarginB="20px" $marginB="40px" $marginT="10px">
        <CustomizableText
          $margin="0px"
          $size="14px"
          $fontWeight="400"
          $lineHeight="20px"
          $color="#444">
          Set up your 2FA and make your account more secure.
        </CustomizableText>
      </Wrapper>
      <form action="">
        <Wrapper $display="flex" $justify="space-between">
          <Wrapper $mobileWidth="100%" $width="48%" $display="flex" $direction="column" $gap="10px">
            <CustomizableText
              $color="#2A2A2A"
              $margin="0px"
              $size="14px"
              $fontWeight="500"
              $lineHeight="20px">
              Current Password
            </CustomizableText>
            <TextField type="password" defaultValue={'@123456789#'} />
          </Wrapper>
        </Wrapper>
        <Wrapper
          $marginB="20px"
          $marginT="25px"
          $display="flex"
          $justify="space-between"
          $mobileColumn="column"
          $gap="30px">
          <Wrapper $width="50%" $mobileWidth="100%" $display="flex" $direction="column" $gap="10px">
            <CustomizableText
              $color="#2A2A2A"
              $margin="0px"
              $size="14px"
              $fontWeight="500"
              $lineHeight="20px">
              New Password
            </CustomizableText>
            <TextField type="password" />
          </Wrapper>
          <Wrapper $width="50%" $mobileWidth="100%" $display="flex" $direction="column" $gap="10px">
            <CustomizableText
              $color="#2A2A2A"
              $margin="0px"
              $size="14px"
              $fontWeight="500"
              $lineHeight="20px">
              Confirm Password
            </CustomizableText>
            <TextField type="password" />
          </Wrapper>
        </Wrapper>
        <Button variant="contained" disabled sx={{ fontWeight: 600, marginBottom: '30px' }}>
          Change Password
        </Button>
      </form>
      <CustomizableText
        $margin="0px"
        $size="20px"
        $fontWeight="700"
        $lineHeight="32px"
        $color="#000759">
        Account Activity
      </CustomizableText>
      <Wrapper $marginB="40px" $marginT="10px">
        <CustomizableText
          $margin="0px"
          $size="14px"
          $fontWeight="400"
          $lineHeight="20px"
          $color="#444">
          Set up your 2FA and make your account more secure.
        </CustomizableText>
      </Wrapper>
      <AccountActivity />
      <Wrapper $marginT="30px" $display="flex" $justify="flex-end">
        <Button variant="contained" disabled sx={{ fontWeight: 600, marginBottom: '30px' }}>
          Save Changes
        </Button>
      </Wrapper>
    </SecurityWrapper>
  );
};

export default SecurityComponent;
